services:
  postgres:
    container_name: expensives-control-db
    image: postgres:17.0
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local

networks:
  external_net:
    external: true
